name: Generate PDF from LaTeX

on:
  workflow_dispatch:
  
  push:
    paths:
      - '**/Roles/*/main.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Compile LaTeX to PDF and Rename
        run: |
          shopt -s globstar
          for tex_file in Roles/**/main.tex; do
            parent_folder=$(dirname "$tex_file")
            parent_folder_name=$(basename "$parent_folder")
            xelatex -interaction=nonstopmode "$tex_file"
            mv main.pdf Nandan_M_"$parent_folder_name".pdf
            mv Nandan_M_"$parent_folder_name".pdf "$parent_folder"
          done

      - name: Get current branch name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $NF}')" >> $GITHUB_ENV

      - name: Check if not main/master branch
        id: not_main_master
        run: |
          if [ "${BRANCH_NAME}" != "main" ] && [ "${BRANCH_NAME}" != "master" ]; then
            echo "Not on main or master branch"
            echo "SKIP_JOB=false" >> $GITHUB_ENV
          else
            echo "On main or master branch. Skipping the job."
            echo "SKIP_JOB=true" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        run: |
          gh release create -t "Release Nandan_M_${BRANCH_NAME}" -n "Release assets" -F Nandan_M_${BRANCH_NAME}.pdf

      - name: Delete Previous Releases
        run: |
          releases=$(gh release list | awk '{print $1}')
          for release in $releases; do
            gh release delete $release -y
          done
