name: Generate PDF from LaTeX

on:
  workflow_dispatch:
  
  push:
    paths:
      - main.tex
      - rahulworld-resume.cls

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Compile LaTeX to PDF with XeLaTeX
        run: |
          xelatex -interaction=nonstopmode main.tex

      - name: Get current branch name
        id: branch_name
        run: echo "::set-output name=name::$(echo $GITHUB_REF | awk -F'/' '{print $NF}')"

      - name: Check if not main/master branch
        id: not_main_master
        run: |
          if [ "${{ steps.branch_name.outputs.name }}" != "main" ] && [ "${{ steps.branch_name.outputs.name }}" != "master" ]; then
            echo "Not on main or master branch"
            echo "::set-output name=skip::false"
          else
            echo "On main or master branch. Skipping the job."
            echo "::set-output name=skip::true"
          fi

      - name: Rename PDF File
        run: |
          mv main.pdf Nandan_M_${{ steps.branch_name.outputs.name }}.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: Resume_Nandan_M_${{ steps.branch_name.outputs.name }}
          path: Nandan_M_${{ steps.branch_name.outputs.name }}.pdf
