name: Generate PDF from LaTeX

on:
  workflow_dispatch:

  push:
    paths:
      - '**/Roles/*/main.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Compile LaTeX to PDF and Rename
        run: |
          shopt -s globstar
          for tex_file in Roles/**/main.tex; do
            parent_folder=$(dirname "$tex_file")
            parent_folder_name=$(basename "$parent_folder")

            echo "Compiling $tex_file in $parent_folder"
            ls -l "$parent_folder"

            # Set the working directory to the parent folder
            cd "$parent_folder"

            xelatex -interaction=nonstopmode main.tex
            mv main.pdf Nandan_M_"$parent_folder_name".pdf
            mv Nandan_M_"$parent_folder_name".pdf ..

            # Return to the repository root
            cd -
          done

      - name: Create GitHub Release
        run: |
          release_name="Release_$(date +'%Y%m%d%H%M%S')"
          gh release create "$release_name" Nandan_M*.pdf -t "$release_name" -n "Release assets"

      - name: Clean up - Remove intermediate PDFs
        run: |
          find Roles -type f -name "Nandan_M*.pdf" -delete