name: Generate PDF from LaTeX

on:
  workflow_dispatch:
  
  push:
    paths:
      - '**/main.tex'
      - '**/rahulworld-resume.cls'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Compile LaTeX to PDF with XeLaTeX
        run: |
          xelatex -interaction=nonstopmode main.tex

      - name: Get current branch name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $NF}')" >> $GITHUB_ENV

      - name: Check if not main/master branch
        id: not_main_master
        run: |
          if [ "${BRANCH_NAME}" != "main" ] && [ "${BRANCH_NAME}" != "master" ]; then
            echo "Not on main or master branch"
            echo "SKIP_JOB=false" >> $GITHUB_ENV
          else
            echo "On main or master branch. Skipping the job."
            echo "SKIP_JOB=true" >> $GITHUB_ENV
          fi

      - name: Rename PDF File
        if: env.SKIP_JOB != 'true'
        run: |
          mv main.pdf Nandan_M_${BRANCH_NAME}.pdf

      - name: Upload PDF artifact
        if: env.SKIP_JOB != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: Resume_Nandan_M_${BRANCH_NAME}
          path: Nandan_M_${BRANCH_NAME}.pdf
