name: Generate PDF from LaTeX

on:
  push:
    paths:
      - main.tex
      - rahulworld-resume.cls

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Compile LaTeX to PDF with XeLaTeX
        run: |
          xelatex -interaction=nonstopmode main.tex

      - name: Rename PDF File
        run: |
          mv main.pdf Nandan_M.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: Resume_Nandan_M
          path: Nandan_M.pdf  # PDF file name
