name: Generate PDF from LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Compile LaTeX to PDF
        run: |
          pdflatex -interaction=nonstopmode main.tex  # Replace with your actual LaTeX file name

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: Nandan_M.pdf  # PDF file name
